<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ArtisanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                # Artisan 1
                'name' => 'Carlos',
                'last_name' => 'Gómez',
                'email' => 'carlos@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1990-05-12',
                'gender' => 'male',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Centro',
                'address' => 'Cra 45 #12-34',
                'phone' => '3001234567',
                'latitude' => 10.12345678,
                'longitude' => -75.12345678,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 2
                'name' => 'Ana',
                'last_name' => 'Pérez',
                'email' => 'ana@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1985-09-30',
                'gender' => 'female',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'San José',
                'address' => 'Calle 20 #8-50',
                'phone' => '3109876543',
                'latitude' => 9.32123456,
                'longitude' => -75.32123456,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 3
                  'name' => 'Juan',
                'last_name' => 'Pérez',
                'email' => 'juan@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1953-01-20',
                'gender' => 'male',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Calle Real',
                'address' => 'Carrera 6 #5-40',
                'phone' => '3134573543',
                'latitude' => 9.1821,
                'longitude' =>  -75.3824,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),

            ],
            [
                # Artisan 4
                  'name' => 'Patricia',
                'last_name' => 'Cordoba',
                'email' => 'patricia@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1953-01-20',
                'gender' => 'female',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'El Oasis',
                'address' => 'Carrera 8 #17-22',
                'phone' => '3144214543',
                'latitude' => 9.1845,
                'longitude' =>  -75.3842,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 5
                  'name' => 'Fernando',
                'last_name' => 'Mejía',
                'email' => 'fernando@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1999-08-03',
                'gender' => 'male',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Fatima',
                'address' => 'Calle 19 #6-80',
                'phone' => '3135678901',
                'latitude' => 9.1817,
                'longitude' =>  -75.3816,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 6
                'name' => 'Diana',
                'last_name' => 'Salas',
                'email' => 'diana@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1891-03-02',
                'gender' => 'female',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Nueve de Marzo',
                'address' => 'Carrera 5 #21-34',
                'phone' => '3146789012',
                'latitude' => 9.1839,
                'longitude' =>  -75.3827,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 7
                'name' => 'Andrés',
                'last_name' => 'Navarro',
                'email' => 'andres@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1983-03-19',
                'gender' => 'male',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Villa Marta',
                'address' => 'Calle 22 #7-18',
                'phone' => '3157890123',
                'latitude' => 9.1842,
                'longitude' =>  -75.3838,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 8
                'name' => 'Sandra',
                'last_name' => 'Patiño',
                'email' => 'sandra@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1991-11-11',
                'gender' => 'female',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Las palmas',
                'address' => 'Carrera 9 #19-15',
                'phone' => '3168901234',
                'latitude' => 9.1828,
                'longitude' =>  -75.3846,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 9
                'name' => 'Javier',
                'last_name' => 'Quiroz',
                'email' => 'javier@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1987-08-27',
                'gender' => 'male',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'San José',
                'address' => 'Calle 21 #9-70',
                'phone' => '3179012345',
                'latitude' => 9.1835,
                'longitude' =>  -75.3799,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 10
                'name' => 'Lina',
                'last_name' => 'Pérez',
                'email' => 'lina@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1993-10-03',
                'gender' => 'female',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Las acacias',
                'address' => 'Carrera 7 #6-35',
                'phone' => '3180123456',
                'latitude' => 9.1815,
                'longitude' =>  -75.3829,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 11
                'name' => 'Óscar',
                'last_name' => 'Romero',
                'email' => 'oscar@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1982-05-12',
                'gender' => 'male',
                'residence_municipality' => 'Sampués',
                'neighborhood' => 'Villa Marta',
                'address' => 'Calle 23 #8-10',
                'phone' => '3191234567',
                'latitude' => 9.1840,
                'longitude' => -75.3840,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 12
                'name' => 'Tatiana',
                'last_name' => 'Herrera',
                'email' => 'tatiana@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1995-02-28',
                'gender' => 'female',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'La Parroquia',
                'address' => 'Calle 20 #8-52',
                'phone' => '3202345678',
                'latitude' => 9.3327,
                'longitude' => -75.3036,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 13
                'name' => 'Héctor',
                'last_name' => 'Zapata',
                'email' => 'hector@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1984-07-07',
                'gender' => 'male',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'La Cruz',
                'address' => 'Carrera 8 #18-11',
                'phone' => '3213456789',
                'latitude' => 9.3348,
                'longitude' => -75.3042,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 14
                'name' => 'Yolanda',
                'last_name' => 'Moreno',
                'email' => 'yolanda@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1986-04-09',
                'gender' => 'female',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Alta Cruz',
                'address' => 'Calle 19 #7-68',
                'phone' => '3224567890',
                'latitude' => 9.3355,
                'longitude' => -75.3063,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 15
                'name' => 'Miguel',
                'last_name' => 'López',
                'email' => 'miguel@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1978-10-26',
                'gender' => 'male',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Rincón',
                'address' => 'Carrera 5 #22-10',
                'phone' => '3235678901',
                'latitude' => 9.3316,
                'longitude' => -75.3031,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 16
                'name' => 'Paola',
                'last_name' => 'García',
                'email' => 'paola@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1992-09-01',
                'gender' => 'female',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Chambacú',
                'address' => 'Carrera 6 #4-55',
                'phone' => '3246789012',
                'latitude' => 9.3330,
                'longitude' => -75.3057,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 17
                'name' => 'Ricardo',
                'last_name' => 'Morales',
                'email' => 'ricardo@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1981-03-03',
                'gender' => 'male',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Calle baja',
                'address' => 'Calle 22 #6-23',
                'phone' => '3257890123',
                'latitude' => 9.3345,
                'longitude' => -75.2929,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 18
                'name' => 'Claudia',
                'last_name' => 'Martinez',
                'email' => 'claudia@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1989-06-20',
                'gender' => 'female',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'San Francisco',
                'address' => 'Carrera 9 #20-03',
                'phone' => '3268901234',
                'latitude' => 9.3321,
                'longitude' => -75.3048,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 19
                'name' => 'Pedro',
                'last_name' => 'Castillo',
                'email' => 'pedro@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1980-12-12',
                'gender' => 'male',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Candelaria',
                'address' => 'Calle 21 #8-44',
                'phone' => '3179012345',
                'latitude' => 9.3350,
                'longitude' => -75.2924,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ],
            [
                # Artisan 20
                'name' => 'Luisa',
                'last_name' => 'Torres',
                'email' => 'luisa@cr.com',
                'password' => Hash::make('123456789'),
                'role' => 'artisan',
                'birth_date' => '1994-05-18',
                'gender' => 'female',
                'residence_municipality' => 'Morroa',
                'neighborhood' => 'Los Olivos',
                'address' => 'Carrera 7 #17-90',
                'phone' => '3110123456',
                'latitude' => 9.3333,
                'longitude' => -75.2933,
                'profile_photo' => null,
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]
        ]);
    }
}
